version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
  db:
    image: mysql:8.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=password123!
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password123!
